name: build

on: [push, pull_request]

env:
  PROJECT: Hourglass
  NAUDIO: Hourglass.NAudio
  NAUDIO_ARTIFACT: NAudioHourglassPack
  CONFIGURATION_RELEASE: Release
  CONFIGURATION_RELEASE_PORTABLE: Release Portable
  FW: net48
  COMPRESSION_LEVEL: 9
  RETENTION_DAYS: 30

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Set up

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.3.2

    # Check out

    - name: Check out ${{env.PROJECT}}
      uses: actions/checkout@v4.1.1

    # Restore

    - name: Restore ${{env.PROJECT}}.sln
      run: dotnet restore ${{env.PROJECT}}.sln

    # Build

    - name: Build ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}}
      run: msbuild /p:Configuration="${{env.CONFIGURATION_RELEASE_PORTABLE}}" ${{env.PROJECT}}.sln

    - name: Build ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE}}
      run: msbuild /p:Configuration="${{env.CONFIGURATION_RELEASE}}" ${{env.PROJECT}}.sln

    # Test

    - name: Test ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}}
      run: dotnet test --configuration "${{env.CONFIGURATION_RELEASE_PORTABLE}}" --no-build --verbosity normal

    - name: Create ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}} test report
      uses: dorny/test-reporter@v1.9.1
      if: ${{success() || failure()}}
      with:
        name: tests
        path: '**/*.trx'
        reporter: dotnet-trx

    # Upload artifacts

    - name: Publish ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE}} Installer
      uses: actions/upload-artifact@v4.4.0
      with:
        name: ${{env.PROJECT}}Installer
        path: |
          ${{env.PROJECT}}.Bundle/bin/${{env.CONFIGURATION_RELEASE}}/${{env.PROJECT}}Installer.exe
        compression-level: ${{env.COMPRESSION_LEVEL}}
        retention-days: ${{env.RETENTION_DAYS}}

    - name: Publish ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}}
      uses: actions/upload-artifact@v4.4.0
      with:
        name: ${{env.PROJECT}}Portable
        path: |
          ${{env.PROJECT}}/bin/${{env.CONFIGURATION_RELEASE_PORTABLE}}/${{env.FW}}/${{env.PROJECT}}.exe
          ${{env.PROJECT}}/bin/${{env.CONFIGURATION_RELEASE_PORTABLE}}/${{env.FW}}/${{env.PROJECT}}.exe.config
          ${{env.PROJECT}}/bin/${{env.CONFIGURATION_RELEASE_PORTABLE}}/${{env.FW}}/ngen-${{env.PROJECT}}.bat
        compression-level: ${{env.COMPRESSION_LEVEL}}
        retention-days: ${{env.RETENTION_DAYS}}

    - name: Publish ${{env.NAUDIO}}
      uses: actions/upload-artifact@v4.4.0
      with:
        name: ${{env.NAUDIO_ARTIFACT}}
        path: |
          ${{env.NAUDIO}}/bin/${{env.CONFIGURATION_RELEASE}}/${{env.FW}}/Hourglass.NAudio.dll
          ${{env.NAUDIO}}/bin/${{env.CONFIGURATION_RELEASE}}/${{env.FW}}/Microsoft.Win32.Registry.dll
          ${{env.NAUDIO}}/bin/${{env.CONFIGURATION_RELEASE}}/${{env.FW}}/NAudio.dll
          ${{env.NAUDIO}}/bin/${{env.CONFIGURATION_RELEASE}}/${{env.FW}}/NAudio.Core.dll
          ${{env.NAUDIO}}/bin/${{env.CONFIGURATION_RELEASE}}/${{env.FW}}/NAudio.Wasapi.dll
          ${{env.NAUDIO}}/bin/${{env.CONFIGURATION_RELEASE}}/${{env.FW}}/NAudio.WinMM.dll
        compression-level: ${{env.COMPRESSION_LEVEL}}
        retention-days: ${{env.RETENTION_DAYS}}
