name: build

on: [push, pull_request]

env:
  PROJECT: Hourglass
  CONFIGURATION_RELEASE: Release
  CONFIGURATION_RELEASE_PORTABLE: Release Portable
  RETENTION_DAYS: 30

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Set up

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.3.2

    # Check out

    - name: Check out ${{env.PROJECT}}
      uses: actions/checkout@v4.1.1

    # Restore

    - name: Restore ${{env.PROJECT}}.Test
      run: dotnet restore ${{env.PROJECT}}.Test\${{env.PROJECT}}.Test.csproj

    # Build

    - name: Build ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}}
      run: msbuild /p:Configuration="${{env.CONFIGURATION_RELEASE_PORTABLE}}" ${{env.PROJECT}}.sln

    - name: Build ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE}}
      run: msbuild /p:Configuration="${{env.CONFIGURATION_RELEASE}}" ${{env.PROJECT}}.sln

    # Test

    - name: Test ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}}
      run: dotnet test --configuration "${{env.CONFIGURATION_RELEASE_PORTABLE}}" --no-build --verbosity normal

    - name: Create ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}} test report
      uses: dorny/test-reporter@v1.9.1
      if: ${{success() || failure()}}
      with:
        name: tests
        path: '**/*.trx'
        reporter: dotnet-trx

    # Upload artifacts

    - name: Publish ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE}} Installer
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{env.PROJECT}}Installer
        path: |
          ${{env.PROJECT}}.Bundle/bin/${{env.CONFIGURATION_RELEASE}}/${{env.PROJECT}}Installer.exe
        retention-days: ${{env.RETENTION_DAYS}}

    - name: Publish ${{env.PROJECT}} ${{env.CONFIGURATION_RELEASE_PORTABLE}}
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{env.PROJECT}}Portable
        path: |
          ${{env.PROJECT}}/bin/${{env.CONFIGURATION_RELEASE_PORTABLE}}/net48/${{env.PROJECT}}.exe
          ${{env.PROJECT}}/bin/${{env.CONFIGURATION_RELEASE_PORTABLE}}/net48/${{env.PROJECT}}.exe.config
          ${{env.PROJECT}}/bin/${{env.CONFIGURATION_RELEASE_PORTABLE}}/net48/ngen-${{env.PROJECT}}.bat
        retention-days: ${{env.RETENTION_DAYS}}
